"""Crash-safe storage for campaign plans, checkpoints, and simulations."""

from pathlib import Path
from .campaign import CampaignPlan, CampaignState, RoundRecord
from .config import CampaignProject
from .coverage import CoverageGrid
from .profiles import SimulationResult

class SQLiteCampaignStore:
    path: str
    def __init__(self, path: str | Path) -> None: ...
    def close(self) -> None: ...
    def load_plan(self, campaign_id: str) -> CampaignPlan | None: ...
    def save_plan(self, plan: CampaignPlan) -> None: ...
    def load_state(self, campaign_id: str) -> CampaignState | None: ...
    def save_state(self, campaign_id: str, state: CampaignState) -> None: ...
    def save_simulation(self, campaign_id: str, result: SimulationResult) -> None: ...
    def covered_bins(self, campaign_id: str, grid: CoverageGrid) -> frozenset[int]: ...
    def save_round(self, campaign_id: str, record: RoundRecord, state: CampaignState) -> None: ...
    def load_revision(self, campaign_id: str, plan_revision: int) -> CampaignProject | None: ...
    def latest_revision(self, campaign_id: str) -> CampaignProject | None: ...
    def save_revision(self, project: CampaignProject, source_generation_id: str | None = ...) -> None: ...
    def latest_generation(self, campaign_id: str, plan_revision: int) -> str | None: ...
    def campaign_generation_ids(self, campaign_id: str) -> tuple[str, ...]: ...
    def generation_exists(self, campaign_id: str, run_generation_id: str) -> bool: ...
    def generation_fingerprint(self, campaign_id: str, run_generation_id: str) -> str | None: ...
    def load_generation_state(self, campaign_id: str, run_generation_id: str, plan_revision: int) -> CampaignState | None: ...
    def create_generation(self, campaign_id: str, run_generation_id: str, plan_revision: int, simulation_fingerprint: str, state: CampaignState) -> None: ...
    def save_generation_state(self, campaign_id: str, run_generation_id: str, plan_revision: int, state: CampaignState) -> None: ...
    def load_generation_simulation(self, campaign_id: str, run_generation_id: str, simulation_fingerprint: str, signature_id: str, seed: int) -> SimulationResult | None: ...
    def save_generation_simulation(self, campaign_id: str, run_generation_id: str, simulation_fingerprint: str, plan_revision: int, result: SimulationResult) -> None: ...
    def generation_covered_bins(self, campaign_id: str, run_generation_id: str, grid: CoverageGrid) -> frozenset[int]: ...
    def generation_round_count(self, campaign_id: str, run_generation_id: str) -> int: ...
    def save_generation_round(self, campaign_id: str, run_generation_id: str, plan_revision: int, record: RoundRecord, state: CampaignState) -> None: ...
