"""Orchestration only: probes -> sensitivity -> update -> three-seed verification.

No geometry, score formula, subprocess command, or serialization implementation
belongs here. Store and simulator are injected; old campaigns are never mutated.
Stored plans and state fingerprints guard resume inputs; the campaign continues
until cumulative grid coverage, a terminal decision/failure, or feature saturation.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal, Protocol
from .models import FeatureBlock, Signature
from .coverage import CoverageGrid, CoverageResult
from .euler import DensitySweepCursor, FeatureBound, OrientationSweepCursor, ProbeEvidence, RepeatabilityResult, UpdateProposal, UpdateRule
from .ports import Simulator
from .profiles import SimulationResult

if TYPE_CHECKING:
    from .config import CampaignProject

@dataclass(frozen=True)
class CampaignPlan:
    campaign_id: str
    start_signatures: tuple[Signature, ...]
    grid: CoverageGrid
    bounds: tuple[FeatureBound, ...]
    exploration_seed: int
    verification_seeds: tuple[int, int, int]
    update_rule_id: str = ...
    @property
    def initial_parent(self) -> Signature: ...

@dataclass(frozen=True)
class RoundRecord:
    round_index: int
    block: FeatureBlock
    parent_coverage: CoverageResult
    probes: tuple[ProbeEvidence, ...]
    proposal: UpdateProposal
    verification: RepeatabilityResult | None
    lineage_start_signature_id: str

@dataclass(frozen=True)
class LineageState:
    start_signature_id: str
    parent: Signature
    next_block: FeatureBlock
    next_round_index: int
    blocked_features: tuple[str, ...]
    status: Literal["ready", "running", "stopped", "decision_required", "failed"]
    reason: str | None
    density_step_scale: float = ...
    orientation_cursors: tuple[OrientationSweepCursor, ...] = ...
    size_sample_count: int = ...
    density_cursors: tuple[DensitySweepCursor, ...] = ...

@dataclass(frozen=True)
class CampaignState:
    campaign_id: str
    plan_fingerprint: str
    active_lineage_index: int
    lineages: tuple[LineageState, ...]
    status: Literal["ready", "running", "coverage_complete", "round_budget_exhausted", "all_lineages_saturated", "stopped", "decision_required", "failed"]
    reason: str | None
    @property
    def active_lineage(self) -> LineageState: ...
    @property
    def parent(self) -> Signature: ...
    @property
    def next_block(self) -> FeatureBlock: ...
    @property
    def next_round_index(self) -> int: ...
    @property
    def blocked_features(self) -> tuple[str, ...]: ...

@dataclass(frozen=True)
class CampaignResult:
    state: CampaignState
    rounds: tuple[RoundRecord, ...]
    plan_revision: int | None = ...
    run_generation_id: str | None = ...

class CampaignStore(Protocol):
    def load_plan(self, campaign_id: str) -> CampaignPlan | None: ...
    def save_plan(self, plan: CampaignPlan) -> None: ...
    def load_state(self, campaign_id: str) -> CampaignState | None: ...
    def save_state(self, campaign_id: str, state: CampaignState) -> None: ...
    def save_simulation(self, campaign_id: str, result: SimulationResult) -> None: ...
    def covered_bins(self, campaign_id: str, grid: CoverageGrid) -> frozenset[int]: ...
    def save_round(self, campaign_id: str, record: RoundRecord, state: CampaignState) -> None: ...

class RevisionCampaignStore(CampaignStore, Protocol):
    def save_revision(self, project: CampaignProject, source_generation_id: str | None = ...) -> None: ...
    def load_revision(self, campaign_id: str, plan_revision: int) -> CampaignProject | None: ...
    def latest_revision(self, campaign_id: str) -> CampaignProject | None: ...
    def latest_generation(self, campaign_id: str, plan_revision: int) -> str | None: ...
    def generation_exists(self, campaign_id: str, run_generation_id: str) -> bool: ...
    def generation_fingerprint(self, campaign_id: str, run_generation_id: str) -> str | None: ...
    def load_generation_state(self, campaign_id: str, run_generation_id: str, plan_revision: int) -> CampaignState | None: ...
    def create_generation(self, campaign_id: str, run_generation_id: str, plan_revision: int, simulation_fingerprint: str, state: CampaignState) -> None: ...
    def save_generation_state(self, campaign_id: str, run_generation_id: str, plan_revision: int, state: CampaignState) -> None: ...
    def load_generation_simulation(self, campaign_id: str, run_generation_id: str, simulation_fingerprint: str, signature_id: str, seed: int) -> SimulationResult | None: ...
    def save_generation_simulation(self, campaign_id: str, run_generation_id: str, simulation_fingerprint: str, plan_revision: int, result: SimulationResult) -> None: ...
    def generation_covered_bins(self, campaign_id: str, run_generation_id: str, grid: CoverageGrid) -> frozenset[int]: ...
    def generation_round_count(self, campaign_id: str, run_generation_id: str) -> int: ...
    def save_generation_round(self, campaign_id: str, run_generation_id: str, plan_revision: int, record: RoundRecord, state: CampaignState) -> None: ...

def validate_plan(plan: CampaignPlan) -> None: ...
def initialize_campaign(plan: CampaignPlan) -> CampaignState: ...
def run_round(plan: CampaignPlan, state: CampaignState, simulator: Simulator, update_rule: UpdateRule, store: CampaignStore) -> RoundRecord: ...
def advance_state(state: CampaignState, record: RoundRecord, *, escalate_density_on_rejection: bool = ...) -> CampaignState: ...
def run_campaign(plan: CampaignPlan, state: CampaignState, simulator: Simulator, update_rule: UpdateRule, store: CampaignStore, *, round_budget: int | None = ..., rounds_already_completed: int = ...) -> CampaignResult: ...
def run_campaign_project(project: CampaignProject, simulator: Simulator, update_rule: UpdateRule, store: RevisionCampaignStore, execution_fingerprint: str | None = ..., *, source_generation_id: str | None = ..., run_generation_id: str | None = ..., force_from_scratch: bool = ...) -> CampaignResult: ...
