"""Typed configuration boundary; no conversion from legacy normal distributions."""

from pathlib import Path
from .models import BartonCategory, CaseSpec
from .campaign import CampaignPlan

def load_barton_categories(path: Path) -> tuple[BartonCategory, ...]: ...
def load_case(path: Path, categories: tuple[BartonCategory, ...]) -> CaseSpec: ...
def save_case(path: Path, case: CaseSpec) -> None: ...
def load_campaign_plan(path: Path) -> CampaignPlan: ...
